### ISSUE TITLE
Marketo

### ISSUE THREAD

**Issue by HamzaWaseemOnBench** [ethyca/fidesops#1077] opened 2022-08-15 12:43 UTC
Specs: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2427650049/Marketo+Connector+Specification

**Comment by Kelsey-Ethyca** [comment] 2022-08-16 16:58
Closing. This is a duplicate of https://github.com/ethyca/fides/issues/1943

**Closed by Kelsey-Ethyca** 2022-08-16 16:58 UTC
Labels: enhancement
